vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        offer_file:
            uri_prefix: /file/offer
            upload_destination: '%kernel.project_dir%/public/file/offer'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        cv_file:
            uri_prefix: /file/cv
            upload_destination: '%kernel.project_dir%/public/file/offer'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
